services:
  # 우리 스프링 앱 서비스
  app:
    build: .
    container_name: deploy-practice-app
    restart: always
    expose:
      - "8080" # 외부 노출 대신 Nginx와 내부 통신만 하도록 변경 추천
    environment:
      - DB_HOST=db
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/practice?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DB_PW}
    depends_on:
      db:
        condition: service_healthy

  # MySQL DB 서비스
  db:
    image: mysql:8.0
    ports:
      - "3307:3306" # 보통 이미 로컬 3306을 사용중일 것을 대비
    environment:
      - MYSQL_DATABASE=practice
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
    volumes:
      - ./mysql_data:/var/lib/mysql # 데이터 유실 방지 (볼륨 마운트)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s

  nginx:
    image: nginx:latest
    container_name: deploy-practice-nginx
    ports:
      - "80:80"   # HTTP (인증용)
      - "443:443" # HTTPS (서비스용)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 24h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: deploy-practice-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
